import Head from "next/head";
import React, { useState, useEffect, useContext } from "react";
import Collection from "../components/Collection";
import Layout from "../components/Layout";
import MintingWidget from "../components/MintingWidget";
import OurArtist from "../components/OurArtist";
import { UserContext } from "../context/context";

export default function Home() {
  const { isConnected } = useContext(UserContext);
  const [mintAmount, setMintAmount] = useState(1);
  const [mintingStatus, setMintingStatus] = useState(false);
  const [maxMintAmount, setMaxMintAmount] = useState(2);
  const [donationAmount, setDonationAmount] = useState();
  const [status, setStatus] = useState(false);

  useEffect(() => {
    setStatus(isConnected);
  }, [isConnected]);

  const decrementMintAmount = () => {
    let newMintAmount = mintAmount - 1;
    if (newMintAmount < 1) {
      newMintAmount = 1;
    }
    setMintAmount(newMintAmount);
  };

  const incrementMintAmount = () => {
    let newMintAmount = mintAmount + 1;
    if (newMintAmount > maxMintAmount) {
      newMintAmount = maxMintAmount;
    }
    setMintAmount(newMintAmount);
  };

  const mintFunction = async () => {
    setMintingStatus(true);

    setMintingStatus(false);
  };

  return (
    <Layout>
      <Head>
        <title>PKPR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-zinc-900">
        <section>
          <div className="mx-auto px-4 py-16 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 lg:grid-cols-2">
              <div className="lg:py-16">
                <OurArtist />
              </div>

              <div className=" flex items-center bg-gray-100">
                <span className="hidden lg:absolute lg:inset-y-0 lg:-left-16 lg:block lg:w-16 lg:bg-gray-100"></span>

                <div className="p-8 sm:p-16 lg:p-24">
                  <h2 className="text-2xl font-Roboto sm:text-3xl">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Tempore, debitis.
                  </h2>

                  <p className="mt-4 font-Raleway text-gray-600">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Aliquid, molestiae! Quidem est esse numquam odio deleniti,
                    beatae, magni dolores provident quaerat totam eos, aperiam
                    architecto eius quis quibusdam fugiat dicta.
                  </p>

                  {status ? (
                    <MintingWidget
                      incrementMintAmount={incrementMintAmount}
                      mintAmount={mintAmount}
                      decrementMintAmount={decrementMintAmount}
                      donationAmount={donationAmount}
                      isMinting={mintingStatus}
                      mintFunction={mintFunction}
                      setDonationAmount={setDonationAmount}
                    />
                  ) : (
                    <div className="flex my-5">
                      <span className="font-Roboto text-2xl text-center text-zinc-900">
                        You must connect your wallet to mint.
                      </span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}
