import Head from "next/head";
import React, { useState, useEffect, useContext } from "react";
import Layout from "../components/Layout";
import MintingWidget from "../components/MintingWidget";
import OurArtist from "../components/OurArtist";
import { UserContext } from "../context/context";
import { useContractRead } from "wagmi";
import contractAbi from "../public/config/ABI.json";

export default function Home() {
  const { isConnected } = useContext(UserContext);
  const [mintAmount, setMintAmount] = useState(1);
  const [maxMintAmount] = useState(2);
  const [donationAmount, setDonationAmount] = useState(0.0);
  const [status, setStatus] = useState(false);
  const [mintStatus, setMintStatus] = React.useState(true);

  useEffect(() => {
    setStatus(isConnected);
  }, [isConnected]);

  const decrementMintAmount = () => {
    let newMintAmount = mintAmount - 1;
    if (newMintAmount < 1) {
      newMintAmount = 1;
    }
    setMintAmount(newMintAmount);
  };

  const incrementMintAmount = () => {
    let newMintAmount = mintAmount + 1;
    if (newMintAmount > maxMintAmount) {
      newMintAmount = maxMintAmount;
    }
    setMintAmount(newMintAmount);
  };

  const { data: pausedData } = useContractRead({
    address: "0xD0fD4E578bB61c9dcbbc567D046DD0AAc4867557",
    abi: contractAbi,
    functionName: "paused",
    watch: true,
  });

  React.useEffect(() => {
    if (pausedData) {
      setMintStatus(pausedData);
    }
  }, [pausedData]);

  return (
    <Layout>
      <Head>
        <title>PKPR Collective | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-zinc-900">
        <section>
          <div className="mx-auto px-4 py-16 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 lg:grid-cols-2">
              <div className="lg:py-16">
                <OurArtist />
              </div>

              <div className=" flex items-center bg-gray-100">
                <span className="hidden lg:absolute lg:inset-y-0 lg:-left-16 lg:block lg:w-16 lg:bg-gray-100"></span>

                <div className="p-8 sm:p-16 lg:p-24">
                  <h2 className="text-2xl font-Roboto sm:text-3xl">
                    Pakistan & Puerto Rico Charity Collective
                  </h2>

                  <p className="mt-4 font-Raleway text-gray-600">
                    9 artists coming together to raise awareness and funds
                    through art about the devastation caused by flooding in
                    Pakistan and Puerto Rico.
                  </p>

                  {status && mintStatus !== true ? (
                    <MintingWidget
                      incrementMintAmount={incrementMintAmount}
                      mintAmount={mintAmount}
                      decrementMintAmount={decrementMintAmount}
                      donationAmount={donationAmount}
                      setDonationAmount={setDonationAmount}
                    />
                  ) : null}

                  {status && mintStatus === true ? (
                    <div className="flex my-5">
                      <span className="font-Roboto text-2xl text-center text-zinc-900">
                        Minting hasnt started yet!
                      </span>
                    </div>
                  ) : null}
                  {!status ? (
                    <div className="flex my-5">
                      <span className="font-Roboto text-2xl text-center text-zinc-900">
                        Please connect your wallet!
                      </span>
                    </div>
                  ) : null}
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}
